/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.perezalcolea.dependency.management;

public class MyLibrary {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new MyLibrary().getGreeting());
    }
}
