/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.perezalcolea.dependency.management;

import com.google.common.collect.ImmutableMap;

import java.util.Map;

public class MyLibrary {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Map items = ImmutableMap.of("coin", 3, "glass", 4, "pencil", 1);
        items.entrySet()
                .stream()
                .forEach(System.out::println);
        System.out.println(new MyLibrary().getGreeting());
    }
}
